server:
  port: 8089
  servlet:
    context-path: /medit
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  config:
    use-legacy-processing: true # 레거시 구동방식 유지
    
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@project-db-cgi.smhrd.com:1524:xe
    username: medit
    password: medit01
    
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    
  devtools:
    livereload:
      enabled: true # 파일을 수정하고 저장되는 순간에 서버 재실행


################# S3 설정 ####################   
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB # 업로드

cloud:
  aws:
    s3:
      bucket: medit-static-files.bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA5GP7S5DFKJJHEPAF
      secret-key: 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
###############################################
  